spring.datasource.master.jdbc-url=jdbc:mysql://localhost:3308/repldb?useSSL=false&serverTimezone=UTC
spring.datasource.master.username=bgpark_master
spring.datasource.master.password=password
spring.datasource.master.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.slave.jdbc-url=jdbc:mysql://localhost:3309/repldb?useSSL=false&serverTimezone=UTC
spring.datasource.slave.username=bgpark
spring.datasource.slave.password=password
spring.datasource.slave.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database=mysql
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update


