spring.h2.console.enabled: true
logging.level.org.hibernate.SQL: debug            # 로그 형식으로 쿼리 보여주기
spring.jpa.properties.hibernate.format_sql: true  # 압축된 쿼리를 읽기 좋게 포멧
spring.jpa.hibernate.ddl-auto: update             # 서버 시작에 테이블 생성
spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password:
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
server:
  port: 8081


# 옵션 추가
# in 쿼리의 개수
# 미리 땡겨오는 개수
# 만약 1이면 총 데이터가 2개일 때, DB에 두번 호출
# 만약 10이면 총 데이터가 100개일 때, DB에 10번 호출